# Generated by Django 5.2.12 on 2026-03-05 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_document_version_index_and_more"),
        ("documents", "1076_savedview_group_by"),
    ]

    operations = []
